jobs:
 - job: terraforminit
   steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'svc-todo-man'
        backendAzureRmStorageAccountName: 'tfstatestorage0202'
        backendAzureRmContainerName: 'todo-cont'
        backendAzureRmKey: 'terraform.tfstate'
