
jobs:
- job: InitJob
  displayName: "Init Job"
  steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      backendServiceArm: 'todo-svc-test'
      backendAzureRmStorageAccountName: 'azurepipeline123'
      backendAzureRmContainerName: 'azure'
      backendAzureRmKey: 'terraform.tfstate'
